### ISSUE TITLE
Ceiling Fan Smart Switch

### ISSUE THREAD

**Issue by wraith1385** [nikshriv/cync_lights#10]
I bought one of the new cync Ceiling Fan Smart Switches.  Attempting to set up the device in HA gets the following error:

2022-09-13 10:30:04.997 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry cync_lights_wraith1385@gmail.com for cync_lights
File "/config/custom_components/cync_lights/__init__.py", line 15, in async_setup_entry
File "/config/custom_components/cync_lights/cync_hub.py", line 26, in __init__
File "/config/custom_components/cync_lights/cync_hub.py", line 26, in <dictcomp>
File "/config/custom_components/cync_lights/cync_hub.py", line 242, in __init__

I downloaded your python program to gather data about the device.  JSON file is attached
[cync_data-main.zip](https://github.com/nikshriv/cync_lights/files/9558151/cync_data-main.zip)

**Comment by nikshriv** [comment]
As of now, I haven't built in any support for ceiling fan switches as they use a different set of commands than the light switches. I don't have any of these devices so I am unable to test, but if you want to help develop support for them, you can check my last post in issue #7 and try doing a packet capture while operating the device with the android app.

**Comment by nikshriv** [comment]
I scanned through the decompiled Android app a little and thus may not be too difficult to implement. It might take me a little while to get to this, but I can give it a try.

**Comment by buckeye1038** [comment]
Has this been implemented? It appears to add these to HA just fine, but the devices do not show in my device list nor any entities for them.
![image](https://user-images.githubusercontent.com/8584102/202886135-9be66ee4-14e4-44f3-9298-eaa9541697c1.png)
![image](https://user-images.githubusercontent.com/8584102/202886186-fb73990e-5414-4abe-8809-3ca83eee5189.png)

**Comment by nikshriv** [comment]
Not implemented. It's proving more difficult than I thought. The code is obscured in the decompiled app, so I haven't been able to parse out.

**Comment by nikshriv** [comment]
Fan switches are now supported. The integration will create a fan speed switch entity.
