### ISSUE TITLE
Dimmer switches not responding 

### ISSUE THREAD

**Issue by jkjunk42** [nikshriv/cync_lights#115]
This integration stopped working for me a few weeks ago. I have 2 dimmer switches no neutral wire. Tried reinstalling and signing in again. Can't get it working.

**Comment by pvlaraia** [comment]
This happened to me too. Tried re-installing the integration a few times and that didn't work. What eventually worked for me was going into the Cync app itself and installing the pending firmware updates for my switch. After that, switches worked again

**Comment by jkjunk42** [comment]
Damn all my devices are up to date.

**Comment by jkjunk42** [comment]
Correction. Apparently they did update. Everything is working again. Wahoo! Closing issue.

**Comment by jkjunk42** [comment]
Closed
