### ISSUE TITLE
Low Priority: Icon for integration throwing 404 error

### ISSUE THREAD

**Issue by rubicon** [nikshriv/cync_lights#13]
The icon in the device integration area is linking to a missing png file.  Wasn't sure if you were aware.

The image file it is pointing to is:  [https://brands.home-assistant.io/cync_lights/dark_icon.png](https://brands.home-assistant.io/cync_lights/dark_icon.png)

**Comment by nikshriv** [comment]
I am aware. My understanding is that Home Assistant doesn't support icons for custom integrations. If I'm wrong, let me know how to fix it... thanks

**Comment by rubicon** [comment]
I'm guessing you just need to do a pull request.

[https://github.com/home-assistant/brands](https://github.com/home-assistant/brands)

They have a bunch of custom integrations in place already. 
[https://github.com/home-assistant/brands/tree/master/custom_integrations](https://github.com/home-assistant/brands/tree/master/custom_integrations)

**Comment by rubicon** [comment]
Looks like someone did this for you about 3 months ago. Closing.
