### ISSUE TITLE
division by zero list index out of range

### ISSUE THREAD

**Issue by jameslb** [nikshriv/cync_lights#15]
Version: f6c7611
```
This error originated from a custom integration.

Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:56
Integration: Cync Lights (documentation)
First occurred: 10:24:55 AM (19 occurrences)
Last logged: 12:16:38 PM

division by zero
list index out of range
Cync client shutting down
```

**Comment by nikshriv** [comment]
Is this causing your integration to stop working? Most of those error messages are for debugging purposes and sometimes they don't mean anything. Is the integration functioning or do the errors you posted correlate with a functional issue?

**Comment by jameslb** [comment]
The integration is still working even with this error in the logs.

With version db99fe9 I now see a slightly different exception in the logs, but the integration is still functioning.

This error originated from a custom integration.

Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:58
Integration: Cync Lights (documentation)
First occurred: 1:59:31 PM (5 occurrences)
Last logged: 2:18:57 PM

ZeroDivisionError: division by zero
