### ISSUE TITLE
Not valid repo?

### ISSUE THREAD

**Issue by articrevised** [nikshriv/cync_lights#17]
I tried installing the repo on a clean install and I'm getting not a valid repo url

**Comment by nikshriv** [comment]
Try pasting this:

https://github.com/nikshriv/cync_lights

**Comment by articrevised** [comment]
Still didn't work

**Comment by nikshriv** [comment]
Are you using HACs or are you trying to add the repo in Home Assistant add ons? If you're not using HACs, you need to install it first. 

https://hacs.xyz/
