### ISSUE TITLE
Is the cloud service only required to install the bulbs in HA?

### ISSUE THREAD

**Issue by Penguin-Guru** [nikshriv/cync_lights#20]
I'm not familiar with how the bulbs communicate. Does this integration control them locally or does it require the cloud service? I would like to deny the bulbs WAN access.

**Comment by nikshriv** [comment]
Yes, the cloud service is the only way this integration is able to control these devices. There is a Cync integration that connects to the Bluetooth mesh that you could use to control them locally so you can block WAN access. I've never tried it myself, so not sure how well it works. 

https://github.com/juanboro/cync2mqtt

**Comment by Penguin-Guru** [comment]
Thank you. :)
