### ISSUE TITLE
Potential Bug

### ISSUE THREAD

**Issue by kevomaco** [nikshriv/cync_lights#26]
I haven't had a chance to work through the logic of the code in full, which is why I'm not making a PR, but on first pass, this looks like a potential bug:
https://github.com/nikshriv/cync_lights/blob/main/custom_components/cync_lights/cync_hub.py#L251

Seems like it should be:
`room.publish_update()`

**Comment by nikshriv** [comment]
Thanks for finding this bug. I'll incorporate your change in the next update. Fortunately, the effect of this bug is minimal. This line dates room states when the integration initiates. The rooms still get updated as the switches update, so no real impact, but still worth fixing.

**Comment by nikshriv** [comment]
This has been updated.
