### ISSUE TITLE
GE CYNC - Dimmer + Motion - Motion/Ambient Not Working

### ISSUE THREAD

**Issue by Anon666333** [nikshriv/cync_lights#27]
Love that this integration was made - so thank you!
Issue:
Motion sensor and ambient light sensor are non-functional.
I attached images, really hoping they show.. 
Something to note, I'm currently using a DIFFERENT motion sensor to activate the switch, which is why the "Kitchen Lights" show they are activated by an automation called "Kitchen Lights - ON - Motion". 

This is my first time writing an issue for anything, so please let me know if you want anything additional and I'm happy to add it! 

The entities exist, however they don't work. I double checked to ensure they work in the CYNC app - they do.
I deleted and reinstalled with no success. 
The switch itself works properly, and is fully controlled by HA with no issue. Just seems to be the sensors. 
I also verified that the sensors work correctly the the native CYNC app. 

HA Core: 2022.11.2
 

![Screenshot_20221117-221248_Home Assistant](https://user-images.githubusercontent.com/99921120/202608481-3f83fdf6-c57d-429d-b085-3ec631be233a.jpg)
![Screenshot_20221117-221242_Home Assistant](https://user-images.githubusercontent.com/99921120/202608483-87c1516e-8cb7-4423-a903-f46de6125417.jpg)
![Screenshot_20221117-221257_Home Assistant](https://user-images.githubusercontent.com/99921120/202608484-74aee284-9cbd-456e-9b0a-6b7d4eac2b6c.jpg)

**Comment by nikshriv** [comment]
Did you enable the motion/ambient light sensor in the Cync app when you installed the switches and configured them?

**Comment by Anon666333** [comment]
> sensor

Yes, they were both on at the time of integration. I also checked them both off in HA during the integration process.

**Comment by nikshriv** [comment]
I'm not sure what's going on.  I do know that the sensors don't function in HA until a motion event or an ambient light change event has taken place after first startup of the integration, but after that, the sensors should work. Can you run my cync_data.py script and tell me your the "deviceType" of your switches? It will be in the output json file.

**Comment by Anon666333** [comment]
I'm so sorry, but can you help me on how to run that?
I was looking at it on Github... But I'm unsure on how to run it.

Have you tested with this switch? If so, can you walk me through how you set it up, from switch install to HA integration? I don't believe I missed anything but I absolutely could have.

**Comment by nikshriv** [comment]
Run the script in a shell or from windows power shell on any computer with Python 3 installed using this command:
“python cync_data.py”

I don’t know which type of switch you have because Cync makes a number of different switches with different device types that look the same. The script should tell you the device type so I can see if yours are different than mine.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nikshriv** [comment]
Also, check your HA logs for errors from the integration and post

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Anon666333** [comment]
I'm not seeing any errors showing up in the HA logs for the Cync sensors. It just states that the sensors are being setup.
`(MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.cync_lights`

I'm so sorry but I'm still struggling to figure out how to run this script of yours.
I tried running it using "python_script" in HA - no output in events because your script uses imports which the native HA py scripting doesn't support.
Tried to install Pyscript to run it, but can't seem to get Pyscript to install.

Any help here would be greatly appreciated...

**Comment by nikshriv** [comment]
I've had a chance to investigate this further. I believe you must be using one of the 3-wire (no neutral wire) switches with motion and ambient light sensor. I recently installed one of these switches in my house as well, and unfortunately it looks like the motion sensor and ambient sensor cannot be supported for this particular device. The device does not report any motion or light changes to the Cync server and appears to only use the sensor information internally.  That is why your motion and light sensors are not working. In the next version, I will remove support for the motion and light sensors for this particular switch.

**Comment by Anon666333** [comment]
Hi there,

Thank you so much for your reply and confirmation!
Makes sense why it doesn't work - pretty odd design choice for this model to keep it all internal. External motion sensors work well so no worries 😊

Kind Regards,

Matt Langlois
________________________________

**Comment by nwithan8** [comment]
> I've had a chance to investigate this further. I believe you must be using one of the 3-wire (no neutral wire) switches with motion and ambient light sensor. I recently installed one of these switches in my house as well, and unfortunately it looks like the motion sensor and ambient sensor cannot be supported for this particular device. The device does not report any motion or light changes to the Cync server and appears to only use the sensor information internally. That is why your motion and light sensors are not working. In the next version, I will remove support for the motion and light sensors for this particular switch.
> 
> Based on my testing, the motion and light sensors do work with the 4-wire switches.

Can confirm, it seems the WiFi wireless motion sensor does not report any data to Cync. Heck, the device doesn't even show up in Cync's app unless you go digging.

I can see via the results of your script that the motion sensor was registered correctly, but its "device info" is simply the two adjacent devices its set to control (one physical light bulb and one virtual room, containing that same light bulb).

I was looking at contributing to your HA integration to potentially fix the motion sensor not appearing as a configurable device, but now I'm doubting that there would even been any data to capture from the device once it were added to HA.

**Comment by glenviewjeff** [comment]
I have the no-neutral device and I swear I verified the ambient light and/or motion sensor actually functioning in my HA setup. Even if it really did function, I don't have any particular need for the feature I suppose, other than maybe to complain to the family over Google Assistant that they left the basement lights on :)
