### ISSUE TITLE
Home Assistant reports this as an invalid repository

### ISSUE THREAD

**Issue by geraldreichelt** [nikshriv/cync_lights#29]
Adding "https://github.com/nikshriv/cync_lights" as add-on repositories in Home Assistant yields the following error, "https://github.com/nikshriv/cync_lights is not a valid add-on repository".  I have been able to add other add-on repositories without issue.  Hope this is fixed soon.

**Comment by nikshriv** [comment]
This is not an add-on. It is an integration. You need to look up how to install a custom integration on Home Assistant. You can either do it manually or you can use HACs.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: geraldreichelt ***@***.***>
Sent: Monday, November 28, 2022 3:40:08 PM
To: nikshriv/cync_lights ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nikshriv/cync_lights] Home Assistant reports this as an invalid repository (Issue #29)


Adding "https://github.com/nikshriv/cync_lights<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnikshriv%2Fcync_lights&data=05%7C01%7C%7C151a2c03a6274f9a1dd508dad199e375%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638052756146318776%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AQeFnNF7sMLdmTKtUFLx0HblLsArKwnEJ7fvpd3RV8I%3D&reserved=0>" as add-on repositories in Home Assistant yields the following error, "https://github.com/nikshriv/cync_lights<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnikshriv%2Fcync_lights&data=05%7C01%7C%7C151a2c03a6274f9a1dd508dad199e375%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638052756146475013%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z82k%2BD4xXE0CE8%2FTCZdlzKmpIUl%2BSgfgM7FmiH7GbC0%3D&reserved=0> is not a valid add-on repository". I have been able to add other add-on repositories without issue. Hope this is fixed soon.

**Comment by geraldreichelt** [comment]
Thank you so much. Being new to HA, this was a little confusing to setup, no fault of your own. I will say, this integration is absolutely incredible. I have been very unhappy with the reliability of these Cync by GE switches. Not just with the integration with the Amazon Echo, but even from the Cync app itself. Voice commands to the echo would fail 25% of the time and about the same with controlling the switches from the Cync app. Sometimes, my echo would say that it couldn't communicate with the switch then 30 seconds later the switch would respond. I just assumed by adding my Cync switches to HA would be one more point of failure, increasing the rate at which my commands failed. This couldn't be further from the truth. You're integration has completely stabilized these switches functionality (I have 37 of these at my house). Now, hey all respond nearly instantaneously to voice commands from my Amazon Echo and from the control panel in the HA app. I don't know how you did it, but you're a genius. Beautiful piece of software.
