### ISSUE TITLE
ge-cync-direct-connect-smart-bulb-full-color-a19-led-smart-light-bulb-wireless

### ISSUE THREAD

**Issue by jameslb** [nikshriv/cync_lights#3]
Hi @nikshriv 

Thank you for putting this integration together.

I have the following bulbs and they report as device type 137.
https://www.gelighting.com/led-lights/bulbs/e26/ge-cync-direct-connect-smart-bulb-full-color-a19-led-smart-light-bulb-wireless

                    "occupancyDeactivationPeriod": 30,
                    "displayName": "Study Top Light",
                    "showOnHome": false,
                    "mac": "MY:DE:BL:TH:MA:CK",
                    "ambientLightEnable": false,
                    "occupancySensitivity": 1,
                    "firmwareVersion": "1.0.313",
                    "occupancyEnable": true,
                    "deviceType": 137,
                    "switchID": 1111111111,
                    "wifiSsid": "WIFISSID",
                    "deviceID": 1111111111111,
                    "commissionedDate": "2022-09-02T21:52:26.106128Z",
                    "wifiMac": "MY:DE:WI:FI:MA:CK",
                    "ambientLightSensitivity": 10,
                    "occupancyTimeoutPeriod": 300

I also noticed an index out of range error when trying to setup the integration. This was due to not finding a wifi compatible device in the home. 

room_controller = home_controllers[home_id][0]

**Comment by nikshriv** [comment]
> Hi @nikshriv
> 
> Thank you for putting this integration together.
> 
> I have the following bulbs and they report as device type 137. https://www.gelighting.com/led-lights/bulbs/e26/ge-cync-direct-connect-smart-bulb-full-color-a19-led-smart-light-bulb-wireless
> 
> ```
>                 "occupancyDeactivationPeriod": 30,
>                 "displayName": "Study Top Light",
>                 "showOnHome": false,
>                 "mac": "MY:DE:BL:TH:MA:CK",
>                 "ambientLightEnable": false,
>                 "occupancySensitivity": 1,
>                 "firmwareVersion": "1.0.313",
>                 "occupancyEnable": true,
>                 "deviceType": 137,
>                 "switchID": 1111111111,
>                 "wifiSsid": "WIFISSID",
>                 "deviceID": 1111111111111,
>                 "commissionedDate": "2022-09-02T21:52:26.106128Z",
>                 "wifiMac": "MY:DE:WI:FI:MA:CK",
>                 "ambientLightSensitivity": 10,
>                 "occupancyTimeoutPeriod": 300
> ```
> 
> I also noticed an index out of range error when trying to setup the integration. This was due to not finding a wifi compatible device in the home.
> 
> room_controller = home_controllers[home_id][0]

I added this device type to the Capabilities lists maintained in the const.py file. This should get your device up and running. Let me know if it doesn't work.

**Comment by jameslb** [comment]
Thanks @nikshriv! I confirmed the additional device type resolved my issue
