### ISSUE TITLE
Switches not triggering from HA

### ISSUE THREAD

**Issue by chicknlil** [nikshriv/cync_lights#31]
I recently added 3 Cync Switches (all 3 way) - 2 that control 1 light, and 1 that controls a single light (I was only able to find the 3-ways, so that's what I used).  They show just fine in the app, and they were added just fine into HA.  However, when I try to trigger them in HA, they don't turn the lights on or off.

There's nothing in the logs that indicate there are any errors - though the logbook is curious:

```
Kitchen Back Switch turned off
1:49:30 PM - 4 minutes ago
Kitchen Back Switch became unavailable
1:49:29 PM - 4 minutes ago
Kitchen Back Switch turned off
1:46:01 PM - 8 minutes ago
Kitchen Back Switch became unavailable
1:46:01 PM - 8 minutes ago
Kitchen Back Switch turned off
1:45:50 PM - 8 minutes ago
Kitchen Back Switch became unavailable
1:45:50 PM - 8 minutes ago
Kitchen Back Switch turned off
1:32:09 PM - 21 minutes ago
Kitchen Back Switch became unavailable
1:32:09 PM - 21 minutes ago
```

Any ideas? The entire reason I had smart switches installed was so I could use them in HA.

**Comment by nikshriv** [comment]
First, make sure you are logged in with the primary Cync account and not a secondary account. 

If that's not the problem, take a look at this issue:

https://github.com/nikshriv/cync_lights/issues/19

Towards the bottom you will see a list of steps to try that may fix your connectivity problem with these devices.

**Comment by chicknlil** [comment]
> First, make sure you are logged in with the primary Cync account and not a secondary account.
> 
> If that's not the problem, take a look at this issue:
> 
> #19
> 
> Towards the bottom you will see a list of steps to try that may fix your connectivity problem with these devices.

I deleted this integration probably a week ago, and just put wifi bulbs into those sockets instead (leaving the Cync switches permenantly on).
