### ISSUE TITLE
Version 822c580 update

### ISSUE THREAD

**Issue by ac0mputerguru** [nikshriv/cync_lights#34]
Howdy! I just updated to 822c580 and I'm having an issue. My setup (via "Cync Central") is: (2) on/off Cync lights (named LR-North and LR-South) in the Living Room area, ie. Living Room entity. On my main Dashboard, I have an entity card that references the Living Room entity, but your latest update caused a duplication error of some kind. The attached picture shows the error I received.
![Cync-00](https://user-images.githubusercontent.com/4010299/211499828-dd0b3221-9806-4381-93a5-7319ce014d81.png)

I went back into cync_lights and refreshed the setup from Cync. This still didn't fix the problem. I rebooted the computer/Home Assistant - no dice. Then, I went into Settings->Integrations and fixed the problem without fully documenting the issue with screen shots. Above screen shot shows the original error, but only the error, not where it was on the entity card. It was right above the Living Room entity.
![Cync-01-Fixed](https://user-images.githubusercontent.com/4010299/211499831-1b566137-6730-4753-a81c-9bcf2ff1d146.png)

So, here's a twist on the same error. Entity card shows there are no errors. But, when I go back into Integrations, you can see the error in the Bedroom area.
![Cync-02png](https://user-images.githubusercontent.com/4010299/211499832-daf035ad-15cf-4832-ad0b-3848a91e1675.png)

Now, this gets a bit messy. The area called Bedroom contains only the Night Stand entity (an on/off wall outlet, the last entity shown). I don't know why the first Bedroom entity was restored, but Living Room was the same way. I had the Kitchen area disabled, which is probably why it wasn't restored. 

My "first try solution" for Living Room was to remove the restored entity (single light bulb icon).
![Cync-03](https://user-images.githubusercontent.com/4010299/211499835-de1e9f3c-ef71-48b0-819e-6bed59b10faa.png)

Finally, I renamed the new light.bedroom_2 back to light.bedroom.
![Cync-04](https://user-images.githubusercontent.com/4010299/211499837-5c1fe1b2-7ef8-42c4-a7aa-ef3c933daddd.png)

Even though I don't use the Kitchen entity, I cleaned it up, as well.
![Cync-05](https://user-images.githubusercontent.com/4010299/211499838-31c20d9c-cdab-4782-9294-71f1ba969219.png)

I hope this is of some help to you and that all is good on your side of this wireless,
William

**Comment by nikshriv** [comment]
Thanks for the info. The new version of the integration required changing some of the core properties of each integration which probably broke your old setup. The unique ids of some of the entities changed and that's why Home Assistant created new entities. There's no easy way that I know of to delete the old devices. You either have to delete them manually (which you did) or you can just delete your current installation and login again. If you do it the second way, your old entities automatically get removed and the new ones show up as intended after logging in again.
