### ISSUE TITLE
 Can't connect despite all bulbs being wifi bulbs

### ISSUE THREAD

**Issue by schilling3003** [nikshriv/cync_lights#35]
I get the following error:
Invalid or unsupported Cync configuration, please ensure there is at least one WiFi connected Cync device in your Home(s)

I have 4 hardwired downlights and 6 of the ST19 Edison bulbs. All of which support WiFi. To confirm WiFi was working I disabled Bluetooth on my phone and can still control the bulbs in the Cync app. When I check the device info of the bulbs in the app they show that one bulb is connected to WiFi and the other bulbs are connecting to that bulb via Bluetooth mesh.

**Comment by nikshriv** [comment]
Try running my cync_data.py script so I can take a look at your configuration data. I just need to see the "deviceType" for your devices to make sure they are listed as Wi-Fi capable. You can post the result here, but be sure to redact sensitive info before posting.

**Comment by schilling3003** [comment]
Thanks for the quick reply. I am new to this, I was able to figure out how to get the python integration running, saved your python script to the python_scripts folder and then call it from developer tools>services, but it does not appear to be creating the json file. Do I need to be editing the python script with my username and password?

**Comment by CaptainKirk55** [comment]
Having the same issue with the newest update. No issues connecting prior and everything else is still working fine with the integration.

cbyge_rooms.json (github doesn't support this filetype so hopefully this is fine)
https://pastebin.com/FEYL3kmG

**Comment by nikshriv** [comment]
> Having the same issue with the newest update. No issues connecting prior and everything else is still working fine with the integration.
> 
> 
> 
> cbyge_rooms.json (github doesn't support this filetype so hopefully this is fine)
> 
> https://pastebin.com/FEYL3kmG

I briefly looked at your configuration, but it looks like parts at the beginning and end were cut off. If you can post the entire output, that would be helpful. Just need to parse the output, but if there are missing parts that could be causing the malfunction, need to see them.

**Comment by schilling3003** [comment]
> Having the same issue with the newest update. No issues connecting prior and everything else is still working fine with the integration.
> 
> cbyge_rooms.json (github doesn't support this filetype so hopefully this is fine) https://pastebin.com/FEYL3kmG

Would you be able to give me an overview of how you ran the python script? I thought I was doing it right, but I'm not getting the JSON file output.

**Comment by nikshriv** [comment]
> > Having the same issue with the newest update. No issues connecting prior and everything else is still working fine with the integration.
> > cbyge_rooms.json (github doesn't support this filetype so hopefully this is fine) https://pastebin.com/FEYL3kmG
> 
> Would you be able to give me an overview of how you ran the python script? I thought I was doing it right, but I'm not getting the JSON file output.

You need to run cync_data.py on your laptop or other computer, not in your Home Assistant instance. You just need to install the latest version of python on your laptop if you don't already have it. Then download the script and run it with "python cync_data.py" in Windows Powershell.  You will probably get some errors because you may not have the dependencies installed. The dependencies can be installed with the command "pip install dependency".

**Comment by schilling3003** [comment]
Thanks! I should be able to figure that out. I thought I needed to run this from within HA.

Thanks again for your help.

**Comment by schilling3003** [comment]
[cbyge_rooms.json.txt](https://github.com/nikshriv/cync_lights/files/10416515/cbyge_rooms.json.txt)

Attached are the results. Let me know if you need anything else.

**Comment by nikshriv** [comment]
Perfect. Figured out the bug, and the newest version should work for you now.

**Comment by schilling3003** [comment]
Thanks! That solved it.
