### ISSUE TITLE
can't set color on cync bulbs

### ISSUE THREAD

**Issue by tedserreyn** [nikshriv/cync_lights#36]
congrats on getting this working!  I finally have control over cync lights and switch that was critical for my automation.

However I cannot seem to set color of bulbs that support it?

**Comment by nikshriv** [comment]
Were you able to get it working?

**Comment by tedserreyn** [comment]
Home Assistant 2023.1.4Supervisor 2022.12.1Operating System 9.4Frontend 20230110.0 - latest

No it doesn’t even initialize:

Logger: homeassistant.components.light
Source: custom_components/hubspace/hubspace.py:89
Integration: Light (documentation, issues)
First occurred: 21:43:33 (1 occurrences)
Last logged: 21:43:33

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 109, in setup_platform
    hs = HubSpace(username,password)
  File "/config/custom_components/hubspace/hubspace.py", line 28, in __init__
    self._refresh_token = self.getRefreshCode()
  File "/config/custom_components/hubspace/hubspace.py", line 89, in getRefreshCode
    session_state = re.search('session_state=(.+?)&code', location).group(1)
  File "/usr/local/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

From: nikshriv ***@***.***>
Date: Saturday, January 14, 2023 at 8:02 PM
To: nikshriv/cync_lights ***@***.***>
Cc: Ted Serreyn ***@***.***>, State change ***@***.***>
Subject: Re: [nikshriv/cync_lights] can't set color on cync bulbs (Issue #36)

Were you able to get it working?

**Comment by tedserreyn** [comment]
Sorry thought this was the hubspaace.    My light problem is tuya, not cync.  The only Cycn I have is switches.  It is working great.

From: nikshriv ***@***.***>
Date: Saturday, January 14, 2023 at 8:02 PM
To: nikshriv/cync_lights ***@***.***>
Cc: Ted Serreyn ***@***.***>, State change ***@***.***>
Subject: Re: [nikshriv/cync_lights] can't set color on cync bulbs (Issue #36)

Were you able to get it working?
