### ISSUE TITLE
Lights suddenly stopped working

### ISSUE THREAD

**Issue by sbtrey23** [nikshriv/cync_lights#41]
I've using this integration with no issues for the entire time I've used Home Assistant (about 2 months) with zero issues. But today, I started getting the below error code. I've tried reconfiguring as well as deleting and re-adding the custom integration, but I keep getting the same error.

This error originated from a custom integration.

Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:65
Integration: Cync Lights (documentation)
First occurred: 5:15:11 PM (3690 occurrences)
Last logged: 5:45:10 PM

KeyError: '468038724'
KeyError: '1911266943'
KeyError: '1593735026'
KeyError: '1012565171'
IndexError: list index out of range

The lights still work through the Cync app and through Google, but they are not working in any of my HA automations.

**Comment by nikshriv** [comment]
Is this still an issue for you? I'm not sure what could have caused those errors. Did you change your configuration? You might try deleting your current configuration, installing the latest version, and then sign in again.

**Comment by sbtrey23** [comment]
> 

I'm not longer having this issue actually. I think the issue is that a lot of my light integrations rely on my house being disarmed, and for some reason, the arm/disarm feature from my security system randomly disappeared. So, when the automations for the lights got to that condition, it couldn't check it, since the arm/disarm entity no long existed. Everything is working great now. Thanks for an awesome integration! I know people like to rag on Cync lights, but I have no issues with them, especially for the price. I'm glad I was able to add them to HA!

On another note, if you don't mind me asking, since the newer lights have bluetooth capability, could they just be added directly via bluetooth? I don't have any bluetooth stuff setup in HA yet, so I can't test it. Just wondering if you knew if that worked.

**Comment by nikshriv** [comment]
I tried to design this integration to use WiFi because not everyone has bluetooth built into their HA server. There is another integration that uses bluetooth to communicate with these devices. You could take a look at https://github.com/juanboro/cync2mqtt if you prefer to connect via bluetooth mesh.
