### ISSUE TITLE
Not a valid add-on repository

### ISSUE THREAD

**Issue by Jedi940** [nikshriv/cync_lights#42]
On a fresh install by downloading the vdi disk from home assistant and running it in virtualbox, I attempted to add your repository and received the error that it was not a valid repository. 

**HA info**
Home Assistant 2023.1.7
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

This may be due to the requirement of a repository.yaml in the root instead of your hacs.json. That was stated in the following link. 
[https://developers.home-assistant.io/docs/add-ons/repository/#:~:text=A%20user%20can%20add%20a,textarea%20and%20click%20on%20Save.](url)

**This is the log entry:**
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:124
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: 9:15:14 PM (1 occurrences)
Last logged: 9:15:14 PM

Failed to to call /store/repositories - https://github.com/nikshriv/cync_lights is not a valid add-on repository

**Comment by nikshriv** [comment]
This integration cannot be installed through the home assistant repository. You can either figure out how to use HACs or just download the integration from github and place them into 'config/custom_components/cync_lights' in your HA instance. You can copy these files to the directory using the File Editor add-on which is probably the simplest way.

**Comment by Jedi940** [comment]
I am simply following the instructions in your readme.  I am not searching through the store.  I clicked on add repository and added the URL to your repo.  

I would also like to add that I forked it, renamed the file to "repository.yaml" and updated it to yaml format and it worked fine.  Thought you should know.

**Comment by Jedi940** [comment]
My apologies, I was mistaken.  I still need the hacs.json that you had for the integration.  You do, however, still need the repository.yaml if you want to be able to add the repo through the GUI.
