### ISSUE TITLE
Cant add new lights HASS

### ISSUE THREAD

**Issue by autonomousperson** [nikshriv/cync_lights#47]
https://pastebin.com/5ykz1yK6 I see your up late with your recent commit... thank you

Ive reset hacs and this plugin, no entities show up

**Comment by autonomousperson** [comment]
commit 50afa93 on 2023.2.4 works after rollback

**Comment by nschimme** [comment]
Same thing occurred to me too

**Comment by nikshriv** [comment]
There was an error in __init__ which is fixed now. Please download the latest version and restart.

**Comment by nschimme** [comment]
Works, thanks!
