### ISSUE TITLE
Light does not turn on

### ISSUE THREAD

**Issue by Menz01** [nikshriv/cync_lights#62]
Hello,
      This has worked for the most part. every now and then it fails and i have to reauthorize and it starts working again. However that is no longer the case. it is no longer working for me. I have redownloaded and re-authorized and still when i click the toggle to turn on the light, the light does not turn on and when i look at HA the toggle is back to off

**Comment by Rajamahal** [comment]
Also having same issue, not able to reauthorize and use anymore. Any resolution?

**Comment by Anon666333** [comment]
Also starting having this same issue as well - started yesterday May 18 2023.
I'm using the Cync Dimmer switch (no neutral) and this was working properly for a long time up until now.
Was there an update done to the Cync platform? I did not see an update from this integration via HACS so I would assume this is Cync making lives harder...again....

**Comment by Rajamahal** [comment]
So I figured out I needed to update the home assistant integration itself
then everything worked again.

**Comment by Menz01** [comment]
That didn't work for me

**Comment by Anon666333** [comment]
I also figured it out... Restarting the switch itself.
Pulled the tab out from the bottom, waited 30 seconds, put it back in, everything came back to life.

Note.. Tech 101 first!

**Comment by Menz01** [comment]
mine is working again now too. weird
