### ISSUE TITLE
Cync Outdoor Plug - Unable to control after a set amount of time.

### ISSUE THREAD

**Issue by BradNagel** [nikshriv/cync_lights#69]
Recently, I picked up a Cync outdoor plug and it does work in Home Assistant with this integration but after a bit of time, it stops responding to commands from HA. While HA can't send commands to the device, it will still respond to changes from the Cyna app or Alexa just fine. Other Cync devices like plugs or lights do not have this issue and will work when the plug stops responding. If I open the Cync app when I have the issue HA will again allow me to connect to the device but after 10 to 20 mins it will again stop working.

I was looking in the logs for more details but couldn't see anything related to Cync. Where is a good place to look for errors so I can provide more detailed info on this issue?

**Comment by network-guy** [comment]
I don't think this is specific to this integration. I have a Cync indoor plug that does the same thing with HA and Google Home. It's probably an issue with the Cync API itself. I have yet to find a solution, but have mostly switched to TP-Link Kasa since they are more reliable and can support energy monitoring.

**Comment by BradNagel** [comment]
Just as an update I discovered that this seemed to be resolved recently after removing a Cync bulb from being used as the wifi bridge. I ended up removing then adding back the bulb from Cync and it seemed to resolve the issue with the outdoor plug completely. Not sure why Alexa or the Cync app worked every time but removing a device or procurement of a device could resolve the problem.
