### ISSUE TITLE
Connection to Cync server reset

### ISSUE THREAD

**Issue by StevenSeiden** [nikshriv/cync_lights#8]
Hi! After setting up the integration, logging in and adding the lights I am experiencing an error. When I try to turn on a light nothing happens. Here is the log:

> Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:38 
Connection to Cync server reset, restarting in 15 seconds
Cync client shutting down

**Comment by nikshriv** [comment]
Are your still logged into the Cync app somewhere else? Unfortunately, the Cync server only allows one device to be logged in at a time and will kick off my HA integration when logged in elsewhere. I have designed the integration to retry logging in every 15 seconds if it gets kicked off to allow you to use the Cync app when needed, but your integration will not work while you're using the Cync app.

**Comment by StevenSeiden** [comment]
I tried logging out of the Cync app everywhere, but I'm still experiencing the issue. Also, if this is noteworthy, it seems that no new logs are being made, so perhaps this issue is unrelated to the log in my previous post, but I can't be sure.
![rec](https://user-images.githubusercontent.com/53193445/189555163-21f6b59e-b7e5-4504-88ca-19b4244b7900.gif)

**Comment by StevenSeiden** [comment]
This error might also be contributing to the problem:

> Traceback (most recent call last):
  File "/config/custom_components/cync_lights/cync_hub.py", line 125, in _maintain_connection
    raise ShuttingDown
custom_components.cync_lights.cync_hub.ShuttingDown

**Comment by nikshriv** [comment]
> I tried logging out of the Cync app everywhere, but I'm still experiencing the issue. Also, if this is noteworthy, it seems that no new logs are being made, so perhaps this issue is unrelated to the log in my previous post, but I can't be sure. Below you can see specifically what happens, where the switch turns back off on its own: ![rec](https://user-images.githubusercontent.com/53193445/189555163-21f6b59e-b7e5-4504-88ca-19b4244b7900.gif) [ ![rec](https://user-images.githubusercontent.com/53193445/189555163-21f6b59e-b7e5-4504-88ca-19b4244b7900.gif) ](https://user-images.githubusercontent.com/53193445/189555163-21f6b59e-b7e5-4504-88ca-19b4244b7900.gif) [ ](https://user-images.githubusercontent.com/53193445/189555163-21f6b59e-b7e5-4504-88ca-19b4244b7900.gif)

Does this happen with all of your device or just this specific one? Does the Desk Lamp actually turn on when you toggle the switch? This behavior occurs when the integration is not receiving the current state of the Desk Lamp. Not sure why that would happen, but will try to investigate...

Would be helpful if you can download my cync_data.py script which is at github.com/nikshriv/cync_data and run it on a computer with python (not your home assistant instance). Then post your cbyge_rooms.json file contents in this thread.

**Comment by StevenSeiden** [comment]
I'm not exactly sure what has happened, but I am now unable to reproduce this error. I really appreciate all of your help and hard work, it isn't going unappreciated :)
