### ISSUE TITLE
Bluetooth bulbs (x3) and WiFi plug (x1) issues using bulbs through integration, but the Cync app works with or w/o bluetooth

### ISSUE THREAD

**Issue by baudneo** [nikshriv/cync_lights#87]
I have seen this issue reported a few times in the past. I have tried all the steps or advice I could find in older issues but, I still can't control the bluetooth bulbs through HASS. I haven't been able to control the bluetooth bulbs at all using the integration since install. The state of the bulbs updates in real time when I am controlling them through the cync app on Android, so there is some communication going on. I can control the WiFi plug via the hass integration, no problems. It's just the bulbs I can't control via this integration. 

The only logs I have seen about the integration have a `list index error` but, that seems to fire when it is getting data from the cync devices/server when I am using the Android app to control the devices. I don't see any errors or any logs at all when trying to control the bulbs. The device just goes back to whatever state it was in before I tried to change it.

```log
Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:231
Integration: Cync Lights ([documentation](https://github.com/nikshriv/cync_lights))
First occurred: 12:00:24 PM (1 occurrences)
Last logged: 12:00:24 PM

IndexError: list index out of range
```

Things I have tried:
- turning bluetooth on my phone off and controlling the bluetooth bulbs using the cync app, which works. In the device settings it says it is connected via the WiFi plug.
- All the steps I could find:
     1. Try using the room switch and the individual device switch to turn them off/on.
     2. Try using the room brightness and individual light brightness to control brightness.
     3. Cycle power for the bulbs and WiFI plug, restart at step 1

Any help would be appreciated, TIA!

**Comment by xsurgefl7x** [comment]
I'm experiencing this same issue. did you find any solution?

**Comment by baudneo** [comment]
> I'm experiencing this same issue. did you find any solution?

Nothing yet. I've tried all the steps outlined in other issues and I still am unable to control the Bluetooth bulbs.

I have not been able to control the Bluetooth bulbs at all since I installed the integration. Only the wifi plug is controllable from HASS.

**Comment by baudneo** [comment]
@nikshriv Any ideas here? Your integration says it works for this use case.

**Comment by baudneo** [comment]
I have created my own LOCAL ONLY cync mqtt add-on: https://github.com/baudneo/cync-lan
