### ISSUE TITLE
Partially working after automatic update 5/4/2024

### ISSUE THREAD

**Issue by JazMTaz** [nikshriv/cync_lights#97]
Devices can be turned on however the icon no longer recognizes that the devices are in the 'on' state and they cannot be turned off.

**Comment by web250** [comment]
Confirming I also have this issue

**Comment by MrJCleary** [comment]
Me too.

**Comment by GreggTom** [comment]
Same problem

**Comment by GreggTom** [comment]
Same here

**Comment by sbs0518** [comment]
Same here.  Though it would seem that HA broke it not the add-in itself.

**Comment by david-j-duran** [comment]
Same. Also log now filling up with lots of errors in last day.

Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:110
integration: Cync Lights ([documentation](https://github.com/nikshriv/cync_lights))
First occurred: May 5, 2024 at 6:25:58 PM (2725 occurrences)
Last logged: 3:40:07 PM
Connection to Cync server reset, restarting in 15 seconds 

This error originated from a custom integration.

Logger: custom_components.cync_lights.cync_hub
Source: custom_components/cync_lights/cync_hub.py:106
integration: Cync Lights (documentation)
First occurred: May 5, 2024 at 6:25:58 PM (2726 occurrences)
Last logged: 3:40:07 PM

RuntimeError: Detected that custom integration 'cync_lights' calls async_write_ha_state from a thread at custom_components/cync_lights/cync_hub.py, line 638: self._update_callback(). Please report it to the author of the 'cync_lights' custom integration.
ShuttingDown:

**Comment by web250** [comment]
There's a fix on #95 which involves editing 4 files.

**Comment by sbs0518** [comment]
@web250, Not seeing the fix.  just a pointer to #94.  Admittedly I'm not a python guy so not entirely clear on the 4 files that need to be adjusted and what the adjustment is.  Really wishing HA provided support for Cync.

**Comment by JazMTaz** [comment]
Same for me, I just removed the existing configuration and repository and added nschimme’s fork at https://github.com/nschimme/cync_lights as the repository and then reinstalled the integration and all is working good again.

**Comment by sbs0518** [comment]
@mmstano, thx but i I am stuck on getting that repo to work.  I've removed the devices, deleted the original integration and have tried to remove the Cync reference in the HACS integration so that I can reinstall from the updated repo but can't seem to get rid of it.

**Comment by mmstano** [comment]
@sbs0518 HACS can be weird sometimes when adding/removing repos. After you remove the repo line in the custom repo window, try restarting home assistant. Then add the new custom repo. You might need to refresh the browser to get it to show up. Then install it and restart home assistant again.

**Comment by sbs0518** [comment]
@mmstano, thank you but I ended up bouncing HA more times that I can recall trying to get it installed.  The only place it still exists in under Settings>Devices & Services>HACS>Services (1 of 12).  Even after deleting the cync_lights folder that was under the custom_components folder.  It's like there's a DB or config entry somewhere that I can't find.  And when I attempt to add the new repo under HACS>3 dot menu>Custom repositories, it will add (initially) but once I restart HA, it's gone...

**Comment by sbs0518** [comment]
Well, the good news is that i got it working using the files from the updated repo (thx for that).  the bad news is it's a bit of a hacked reinstall.  By that I mean (including details here in case someone else can benefit) that I simply downloaded the repo from the https://github.com/nschimme/cync_lights page, extracted them and the uploaded the cync_lights folder and files to the custom_components folder in HA and then re-added the devices.

It survived the restart and actually find (knock on wood) that the dashboard icons actually respond much quicker and accurately reflect the correct state of the devices.  I have Cync switches (not lights) but up until now, I could click one of them in my dashboard and they would take a few seconds to respond or not respond at all, so win-win.

**Comment by GreggTom** [comment]
Working for me also. Thanks

**Comment by jkjunk42** [comment]
I had a rough time with this. Turns out the switches disconnected from the wifi. If you have problems make sure the switches work in the cync app.

**Comment by RichardSchaper** [comment]
I got the nschimme repo installed, and when I try to add devices I am getting an error saying "Invalid or unsupported Cync configuration, please ensure there is at least one WiFi connected Cync device in your Home(s)". However, I have a plug that is connected via wifi.  When I go to logs I am getting:

This error originated from a custom integration.

Logger: custom_components.cync_lights.config_flow
Source: custom_components/cync_lights/config_flow.py:105
integration: Cync Lights (documentation)
First occurred: 12:54:21 AM (6 occurrences)
Last logged: 1:12:26 AM

KeyError: ''

KeyError: ''
